---
  - name: Add repo from Docker
    shell: curl -sSL https://get.docker.com/ubuntu/ | sudo sh creates=/usr/bin/docker
    register: docker

  - name: Install docker
    apt: name=lxc-docker update-cache=yes
    when: docker.changed

  - name: install pip
    apt: name=python-pip state=present update-cache=yes

  - name: make sure pip works
    shell: easy_install -U pip

  - name: install docker-py
    pip: name=docker-py state=present
