- hosts: all
  remote_user: jjohanan
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - swap
    - docker
    - blog_site
    - { role: service_build, service: mysql }
    - { role: service_build, service: nginx }
    - { role: service_build, service: varnish }
    - { role: service_build, service: frontnginx }
    - { role: service_build, service: ejosh, work_dir: /var/www/html }
    - { role: service_build, service: zendfb, work_dir: /var/www-src }

  tasks:
    - include: tasks/docker-compose_rebuild.yml service=frontnginx
    - include: tasks/docker-compose_rebuild.yml service=cadvisor
    - include: tasks/docker-compose_rebuild.yml service=varnish
    - include: tasks/docker-compose_rebuild.yml service=web
    - include: tasks/docker-compose_rebuild.yml service=mysql
    
    - name: bring it all up
      command: chdir={{ work_dir }} docker-compose up -d --no-recreate
    - name: make sure mysql comes up
      pause: seconds=15
    - name: Load blog backup database
      command: docker exec blog_mysql_1 /load_db.sh
    - include: tasks/docker_clean.yml
